[package]
  url = "https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas.git"
  ref = "50.0"
  depth = 1

[[build_configs]]
  build_system = "meson"
  dependencies = ["gobject-introspection@1.86.0"]
