[package]
  ref = "1.2.0.68"

[[build_configs]]
  system_name = "linux"
  system_processor = "x86_64"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/libcuobjclient/linux-x86_64/libcuobjclient-linux-x86_64-1.2.0.68-archive.tar.xz"
