[package]
  url = "https://gitlab.gnome.org/GNOME/libadwaita.git"
  ref = "1.9.2"
  depth = 1

[[build_configs]]
  build_system = "meson"
  system_name = "linux"
  dev_dependencies = ["pkgconf@2.4.3"]
  dependencies = ["glib@2.84.1", "gtk@4.22.0", "appstream@1.1.6"]