[package]
  url = "https://dev.gentoo.org/~blueness/eudev/eudev-3.2.10.tar.gz"
  ref = "3.2.10"
  depth = 1

[[build_configs]]
  build_system = "makefiles"
  system_name_except = "windows"
  dev_dependencies = ["gperf@3.1"]
  options = ["--host=${HOST}"]