[package]
  ref = "13.3.36"

[[build_configs]]
  system_name = "linux"
  system_processor = "x86_64"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/cuda_tileiras/linux-x86_64/cuda_tileiras-linux-x86_64-13.3.36-archive.tar.xz"

[[build_configs]]
  system_name = "windows"
  system_processor = "x86_64"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/cuda_tileiras/windows-x86_64/cuda_tileiras-windows-x86_64-13.3.36-archive.zip"
