[package]
  url = "https://archives.boost.io/release/1.83.0/source/boost_1_83_0.tar.gz"
  ref = "1.83.0"

[[build_configs]]
  build_system = "b2"
  system_names = ["linux", "qnx"]
  options = ["--without-python", "--without-mpi"]

# Note: boost-1.83.0 requires visual studio 2022 or earlier, not supported on VS2026+
