[package]
  url = "https://code.videolan.org/videolan/x264.git"
  ref = "31e19f92f00c7003fa115047ce50978bc98c3a0d"
  depth = 1

[[build_configs]]
  system_name = "linux"
  build_system = "makefiles"
  build_shared = "--enable-shared"
  build_static = "--enable-static"
  patches = ["fix_windows_build.patch"]
  dev_dependencies = ["nasm@2.16.03"]
  options = [
    "--cross-prefix=${CROSSTOOL_PREFIX}",
    "--host=${HOST}",
    "--sysroot=${SYSROOT}",
  ]

[[build_configs]]
  system_name = "windows"
  build_system = "makefiles"
  build_shared = "--enable-shared"
  build_static = "--enable-static"
  patches = ["fix_windows_build.patch"]
  dev_dependencies = ["nasm@2.16.03"]
  options = [
    "--cross-prefix=${CROSSTOOL_PREFIX}",
    "--host=${HOST}",
    "--sysroot=${SYSROOT}",
  ]

[[build_configs]]
  system_name = "qnx"
  build_system = "makefiles"
  build_shared = "--enable-shared"
  build_static = "--enable-static"
  dev_dependencies = ["nasm@2.16.03"]
  options = [
    "--cross-prefix=${CROSSTOOL_PREFIX}",
    "--host=${HOST}",
    "--sysroot=${SYSROOT}",
  ]
  post_configure = [
    "sed -i 's|^DEPFLAGS=.*|DEPFLAGS=|' ${BUILD_DIR}/config.mak",
    "sed -i 's|-I\\$(SRCPATH)/extras||g' ${BUILD_DIR}/config.mak",
  ]