[package]
  ref = "12.3.0.29"

[[build_configs]]
  system_name = "linux"
  system_processor = "x86_64"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/libcufft/linux-x86_64/libcufft-linux-x86_64-12.3.0.29-archive.tar.xz"

[[build_configs]]
  system_name = "windows"
  system_processor = "x86_64"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/libcufft/windows-x86_64/libcufft-windows-x86_64-12.3.0.29-archive.zip"
