[package]
  url = "https://gitlab.freedesktop.org/gstreamer/gstreamer.git"
  ref = "1.28.0"
  depth = 1

[[build_configs]]
  build_system = "meson"
  system_name = "linux"
  build_tools = ["git-lfs"]
  dependencies = [
    "glib@2.84.1",
    "libexpat@2.7.1",
    "openssl@1.1.1w",
    "openxr@3.4.9",
  ]
  dev_dependencies = ["pkgconf@2.4.3", "flex@2.6.4", "bison@3.8.2"]
  options = [
    "-Dpython=disabled",
    "-Dlibxml2:python=false",
    "-Dtests=disabled",
    "-Dexamples=disabled",
    "-Dbenchmarks=disabled",
  ]
