[package]
  url = "https://ftp.gnu.org/gnu/autoconf/autoconf-2.72.tar.xz"
  ref = "2.72"
  build_tool = true

[[build_configs]]
  system_name = "linux"
  build_system = "makefiles"
  dependencies = ["m4@1.4.19"]
  options = ["--disable-nls"]
  envs = [
    "AUTOCONF=:",   # Avoid regenerating configure.ac
    "AUTOMAKE=:",   # Avoid regenerating Makefile.in
    "ACLOCAL=:",    # Avoid regenerating aclocal.m4
    "AUTOHEADER=:", # Avoid regenerating config.h.in
    "MAKEINFO=:",   # Avoid regenerating *.info
  ]