[package]
  url = "https://gitlab.freedesktop.org/xorg/lib/libxpm.git"
  ref = "libXpm-3.5.19"
  depth = 1

[[build_configs]]
  build_system = "makefiles"
  system_name = "linux"
  dev_dependencies = [
    "macros@1.20.2",
    "libtool@2.5.4",
    "pkgconf@2.4.3",
    "gettext@0.25",
  ]
  dependencies = ["xproto@7.0.31", "libx11@1.8.11"]
  envs = ["NOCONFIGURE=1"]
  pre_configure = ["./autogen.sh"]
  options = ["--host=${HOST}"]
