[package]
  url = "https://gitlab.gnome.org/GNOME/gdk-pixbuf.git"
  ref = "2.44.5"
  depth = 1

[[build_configs]]
  build_system = "meson"
  system_name = "linux"
  dependencies = ["shared-mime-info@2.4"]
  options = ["--wrap-mode=nofallback", "-Dglycin=disabled", "-Dman=false"]