[package]
  url = "https://gitlab.gnome.org/GNOME/gdk-pixbuf.git"
  ref = "2.44.5"
  depth = 1

[[build_configs]]
  build_system = "meson"
  system_name_except = "windows"
  dependencies = ["shared-mime-info@2.4"]
  dev_dependencies = ["pkgconf@2.4.3", "glib@2.84.1"]
  options = ["-Dglycin=disabled", "-Dman=false"]