[package]
  url = "https://github.com/openssl/openssl.git"
  ref = "openssl-3.5.0"
  depth = 1
  ignore_submodule = true

# ============= build for aarch64-linux =========== #
[[build_configs]]
  system_name = "linux"
  system_processor = "aarch64"
  build_system = "makefiles"
  build_shared_option = "shared"
  build_static_option = "no-shared"
  options = [
    "linux-aarch64",
    "no-docs",
    "no-demos",
    "no-tests",
    "--openssldir=ssl",
    "--libdir=lib",
  ]

# ============= build for x86_64-linux =========== #
[[build_configs]]
  system_name = "linux"
  system_processor = "x86_64"
  build_system = "makefiles"
  build_shared_option = "shared"
  build_static_option = "no-shared"
  dev_dependencies = ["nasm@2.16.03"]
  options = [
    "linux-x86_64",
    "no-docs",
    "no-demos",
    "no-tests",
    "--openssldir=ssl",
    "--libdir=lib",
  ]

# ============= build for windows =========== #
[[build_configs]]
  system_name = "windows"
  build_system = "makefiles"
  build_tools = ["perl"]
  build_shared_option = "shared"
  build_static_option = "no-shared"
  dev_dependencies = ["nasm@2.16.03"]
  options = [
    "VC-WIN64A",
    "no-docs",
    "no-demos",
    "no-tests",
    "--openssldir=ssl",
    "--libdir=lib"
  ]

# ============== build for QNX ============== #
[[build_configs]]
  system_name = "qnx"
  build_system = "makefiles"
  build_shared_option = "shared"
  build_static_option = "no-shared"
  envs = [
    "CC=ntoaarch64-gcc",
    "CXX=ntoaarch64-g++",
  ]
  post_configure = [
    "sed -i 's|CNF_EX_LIBS=-ldl -pthread|CNF_EX_LIBS=-lsocket -lm -pthread|' ${BUILD_DIR}/Makefile",
  ]
  options = [
    "linux-aarch64",
    "no-tests",
    "no-afalgeng",
    "no-dso",
    "--openssldir=ssl",
    "--libdir=lib",
  ]