[package]
  url = "https://ftp.gnu.org/gnu/help2man/help2man-1.49.3.tar.xz"
  ref = "v1.49.3"

[[build_configs]]
  build_system = "makefiles"
  envs = [
    "AUTOCONF=:",   # Avoid regenerating configure.ac
    "AUTOMAKE=:",   # Avoid regenerating Makefile.in
    "ACLOCAL=:",    # Avoid regenerating aclocal.m4
    "AUTOHEADER=:", # Avoid regenerating config.h.in
    "MAKEINFO=:",   # Avoid regenerating *.info
  ]