[package]
  url = "https://gitlab.freedesktop.org/libevdev/libevdev.git"
  ref = "libevdev-1.13.6"
  depth = 1

[[build_configs]]
  build_system = "meson"
  system_name = "linux"
  dependencies = ["check@0.15.2"]
  options = ["-Ddocumentation=disabled", "-Dtests=disabled", "-Dtools=disabled"]
