[package]
  url = "https://sourceware.org/pub/valgrind/valgrind-3.26.0.tar.bz2"
  ref = "3.26.0"
  depth = 1

[[build_configs]]
  system_name = "linux"
  build_system = "makefiles"
  dev_dependencies = ["macros@1.20.2"]
  pre_configure = ["./autogen.sh"]
  options = ["--host=${HOST}"]