[package]
  url = "https://gitlab.gnome.org/GNOME/gtk.git"
  ref = "4.22.0"
  depth = 1

[[build_configs]]
  build_system = "meson"
  options = [
    "--wrap-mode=nofallback",
    "-Dvulkan=disabled",
    "-Dmedia-gstreamer=disabled",
    "-Dbuild-demos=false",
    "-Dbuild-examples=false",
    "-Dbuild-tests=false",
    "-Dbuild-testsuite=false",
  ]
  dependencies = [
    "glib@2.84.1",
    "shared-mime-info@2.4",
    "cairo@1.18.4",
    "wayland@1.24.0",
    "libxrandr@1.5.4",
    "wayland-protocols@1.44",
    "libxdamage@1.1.6",
    "libepoxy@1.5.4",
    "libtiff@4.1.0",
    "harfbuzz@11.2.1",
    "libjpeg-turbo@3.1.0"
  ]
