# Use archive instead of https://github.com/nigels-com/glew.git, because archive contains pre-generated source files(include/CL/*.h)
[package]
    url = "https://github.com/nigels-com/glew/releases/download/glew-2.3.1/glew-2.3.1.tgz"
    ref = "2.3.1"
    archive = "glew-2.3.1.tgz"
    src_dir = "build/cmake"

[[build_configs]]
    build_system = "cmake"
    options = ["-DBUILD_UTILS=OFF"]
