[package]
  url = "https://gitlab.freedesktop.org/xorg/lib/libxcursor.git"
  ref = "libXcursor-1.2.3"
  depth = 1

[[build_configs]]
  build_system = "makefiles"
  system_name_except = "windows"
  dependencies = [
    "xorgproto@2024.1",
    "libx11@1.8.11",
    "libxfixes@6.0.1",
    "libxrender@0.9.12",
  ]
  dev_dependencies = ["macros@1.20.2"]
  envs = ["NOCONFIGURE=1"]
  pre_configure = ["./autogen.sh"]
  options = ["--host=${HOST}"]