[package]
  url = "https://github.com/google/skcms.git"
  ref = "mirror"

[[build_configs]]
  build_system = "bazel"
  toolchain_name = "gcc"
  patches = ["gcc_fix_copts.patch"]
  options = [
    "//:skcms_public",
  ]

[[build_configs]]
  build_system = "bazel"
  toolchain_name = "clang"
  options = [
    "//:skcms_public",
  ]
