[package]
  url = "https://gitlab.freedesktop.org/gstreamer/gstreamer.git"
  ref = "1.26.0"
  depth = 1

[[build_configs]]
  build_system = "meson"
  system_name = "linux"
  build_tools = ["git-lfs"]
  dependencies = ["boost@1.87.0", "eigen@3.4.0"]
  options = [
    "-Dpython=disabled",
    "-Dlibxml2:python=false",
    "-Dtests=disabled",
    "-Dexamples=disabled",
    "-Dbenchmarks=disabled",
  ]