[package]
  url = "https://gitlab.freedesktop.org/gstreamer/gstreamer.git"
  ref = "1.26.0"
  depth = 1

[[build_configs]]
  build_system = "meson"
  system_name = "linux"
  dependencies = ["openssl@1.1.1w"]
  options = [
    "-Dpython=disabled",
    "-Dlibxml2:python=false",
  ]