[package]
  url = "https://github.com/jarro2783/cxxopts.git"
  ref = "v3.3.1"

[[build_configs]]
  build_system = "cmake"
  options = [
    "-DCXXOPTS_BUILD_EXAMPLES=OFF",
    "-DCXXOPTS_BUILD_TESTS=OFF",
  ]