[package]
  url = "https://github.com/olympus-robotics/mcap_builder.git"
  ref = "main"
  depth = 1

[[build_configs]]
  build_system = "cmake"
  patches = ["fix_cmake.patch"]
  dependencies = ["mcap@1.4.1"]
  options = ["-Dmcap_SOURCE_DIR=${BUILDTREES_DIR}/mcap@1.4.1/src"]
