[package]
  url = "https://ftp.gnu.org/gnu/ncurses/ncurses-6.5.tar.gz"
  ref = "6.5"

[[build_configs]]
  system_name = "linux"
  build_system = "makefiles"
  build_shared_option = "--with-shared"
  options = [
    "--host=${HOST}",
    "--disable-stripping",
    "--with-termlib",
    "--with-normal",
    "--without-tests",
  ]
  post_install_linux = [
    "ln -sf libtinfow.so ${PACKAGE_DIR}/lib/libtinfo.so",
    "ln -sf libncursesw.so ${PACKAGE_DIR}/lib/libncurses.so",
    "ln -sf libformw.so ${PACKAGE_DIR}/lib/libform.so",
    "ln -sf libmenuw.so ${PACKAGE_DIR}/lib/libmenu.so",
    "ln -sf libpanelw.so ${PACKAGE_DIR}/lib/libpanel.so",
  ]

# Note:
# This library support linux only.
