[package]
  url = "https://github.com/seccomp/libseccomp.git"
  ref = "v2.6.0"
  depth = 1

[[build_configs]]
  build_system = "makefiles"
  dev_dependencies = ["macros@1.20.2", "libtool@2.5.4", "gperf@3.1"]
  pre_configure = ["./autogen.sh"]